# Generated by Django 5.0.4 on 2024-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('two_factor_enabled', models.BooleanField(null=True)),
                ('intra_id', models.CharField(max_length=12, null=True, unique=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('avatar', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
