# Generated by Django 5.0.6 on 2024-05-14 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.SmallIntegerField(null=True, unique=True)),
                ('second_factor_enabled', models.BooleanField(default=False)),
                ('second_factor_dict', models.JSONField(db_column='second_factor_dict', default=dict)),
                ('intra_id', models.CharField(max_length=12, null=True, unique=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('avatar', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('alias', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
