openapi: 3.0.2
info:
  title: vault REST API
  version: '1.1.0'
  description: |
    REST API Documentation for ft_transcendence.
    Under heavy development. Expect breaking changes.

servers:
  - url: https://localhost
  - url: https://playpong.duckdns.org

paths:
  /vault/status:
    get:
      tags:
        - Status
      summary: Check Heartbeat Status
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Service is up and running
          content:
            application/json:
              example: {"message": "Service is up and running"}
        '401':
          description: Missing or invalid JWT token
          content:
            application/json:
              example: {"message": "Missing or invalid JWT token"}
        '503':
          description: Service is down or unhealthy
          content:
            application/json:
              example: {"message": "Service is down or unhealthy"}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT