# Generated by Django 5.0.4 on 2024-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('intra_id', models.CharField(max_length=12, null=True)),
                ('username', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('jwt', models.CharField(max_length=255, null=True)),
                ('sub', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
