# Generated by Django 5.0 on 2024-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntraUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('image_url', models.URLField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
