# Generated by Django 5.0 on 2024-02-06 15:32

import intralogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intralogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='intrauser',
            managers=[
                ('objects', intralogin.managers.IntraUserOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
