# Generated by Django 5.0 on 2024-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intralogin', '0004_remove_intrauser_email_remove_intrauser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrauser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='intrauser',
            name='first_name',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='intrauser',
            name='last_name',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='intrauser',
            name='login',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
