# Generated by Django 5.0.3 on 2024-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('intra', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('jwt_token', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
