# Generated by Django 5.0.3 on 2024-03-14 17:50

import intralogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intralogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='intrauser',
            managers=[
                ('objects', intralogin.managers.IntraUserOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='first_name',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='last_name',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='intrauser',
            name='login',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
