# Generated by Django 5.0.3 on 2024-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intralogin', '0002_alter_intrauser_managers_alter_intrauser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrauser',
            name='jwt_token',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
